/**
 * Auto-generated template checksums
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-checksums.js
 */

export const TEMPLATE_CHECKSUMS: Record<string, string[]> = {
  "promptcode-preset-to-prompt.md": [
    "6b33d0542f3f97eb09083fc6d6d6ecab273e2e7d406635c8b2d30c8a3c68b9f1",
    "dc46c41019c808d95fddfa5c6149ce01b117be03ac0b277fc50f61c92c5dedda",
    "99dfa6e473ee885a9ce64d1882fc3f1c989f854095a14597bc8c453f623a4972"
  ],
  "promptcode-preset-list.md": [
    "e1481e4750c5a72d966720803e291b098bb4d41010b814fda034a1406b5b197c",
    "f0e76bf215ecb267d6344f58134e5a39a6833aa3129c83d83ee2f0a5c3471f33"
  ],
  "promptcode-preset-info.md": [
    "70d04d2fe957b360f452cd18a9e7e831957165b6f9a2435ecfb762bc033101c4",
    "da52a33a0efdf19fbad0559babc0844e48d93ed8eef00afb83e8cf7f054a1d7f",
    "d5ae582c010a300fc6a1bfa84191f0f7221f26492b85d1490f2e0bdab4a71ec1"
  ],
  "promptcode-preset-create.md": [
    "68db7f5f5c96b7c5c78dee19fcfafa786f6f2ffa33c0a05d896837a9da77b4a1",
    "5fe5043502b273103d422a945c6181b9136d6ea97e9cfd2282eaa1b96c7c2766",
    "dbc5ffd37033bcd5afaa8edc12fb8b5abc1f0681e2c260957bdd5f2bcd4676c6"
  ],
  "promptcode-ask-expert.md": [
    "202c8932aed700ba14c5fbd1411ef9fde0b1a64b24e315e08743fe384e62dd3b",
    "71ca5ff74847b54ed6a33f6f6a6432730962fb6ef38bf02059a2fd72bbc7fff5",
    "ef78aa1a6554360e0eeae6af575e4edbb2b3d17622c85470ce3c332a9660f1d0",
    "7258ca248659a0dc90eb0604fb7721fc29e47e6d0cbfe5beb2811b11e5511c77"
  ],
  "CLAUDE.md.template": [
    "68ccd663cf594e3335ec9bfefe933c70e0ad210df96ff295e9387aaa5ec90b36",
    "3266e9ac87845042d919de13e44c073d3845ed598badcde86074073311f67fc1",
    "602ce34c60934cbf4e26a976280bceb76fe3bdd55bd7805a6f1ced7d826c4b16",
    "7de6301c41aff4b341902ba2e1a3769201705ec9cd4be4ef1adeb8a79ffa065d"
  ],
  "promptcode-usage.mdc": [
    "8d9e93d903e07848deefd32c10970d214c34f82d05bb938cd4c835a3816d1265",
    "cc9ffcd7bbd5920a9f5d79908c40bc13e3946621cbee24623bc0abf3b334d7e1"
  ],
  "promptcode-preset-to-prompt.mdc": [
    "b7dda66d787c9a056ca3d4743148a56fb2b0652ba2e29a846259245e14c4f3f0",
    "6bafc504afe719f083019025326a95e416d27bf6a32f5edcbc7a5e01e30116e1"
  ],
  "promptcode-preset-list.mdc": [
    "77ed93f774f3d1a47bc5d21342594c68aa7f3fb4733a2e786452b780af65605d"
  ],
  "promptcode-preset-info.mdc": [
    "1fa6ee9037a46bef55039a2f4ec06be5b493833e6efe6de0e2506424170e002d",
    "d9faaeee858e4cdf6c5b6aad2e6f6816eae403db6ea586405a88d4427bab1a39"
  ],
  "promptcode-preset-create.mdc": [
    "65b1edbe2ff662af74feb54acde66965b23c97101b8645194698573f11cc0939",
    "468b8549f45ba8072e15140ff4d1324e11a7c67b7f5a04c74430baa5993ff7ed"
  ],
  "promptcode-ask-expert.mdc": [
    "0f890d74e2da494cee769e9e1b533b8c0386ceb765f245e1d8bd5a73f06a4eb9",
    "919bdae89190e2915c7c5a360a4fde480d4f6a8beb5327d66e89294e8bc591d6"
  ]
};

/**
 * Check if a file content matches any known template version
 */
export function isKnownTemplateVersion(fileName: string, checksum: string): boolean {
  const known = TEMPLATE_CHECKSUMS[fileName];
  return known ? known.includes(checksum) : false;
}

/**
 * Get all known checksums for a template file
 */
export function getKnownChecksums(fileName: string): string[] {
  return TEMPLATE_CHECKSUMS[fileName] || [];
}
