/**
 * Auto-generated template checksums
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-checksums.js
 */

export const TEMPLATE_CHECKSUMS: Record<string, string[]> = {
  "promptcode-preset-to-prompt.md": [
    "dc46c41019c808d95fddfa5c6149ce01b117be03ac0b277fc50f61c92c5dedda"
  ],
  "promptcode-preset-list.md": [
    "e1481e4750c5a72d966720803e291b098bb4d41010b814fda034a1406b5b197c"
  ],
  "promptcode-preset-info.md": [
    "da52a33a0efdf19fbad0559babc0844e48d93ed8eef00afb83e8cf7f054a1d7f"
  ],
  "promptcode-preset-create.md": [
    "105cc9379648d75bc3b3fc2cc99088d89e00d8224f7a774857bb6c0c9f821895",
    "5fe5043502b273103d422a945c6181b9136d6ea97e9cfd2282eaa1b96c7c2766"
  ],
  "promptcode-ask-expert.md": [
    "0ee331e5b6fc770965cf7a0576612831c9ae86613058adabc8a6938cf66b6996",
    "71ca5ff74847b54ed6a33f6f6a6432730962fb6ef38bf02059a2fd72bbc7fff5"
  ],
  "CLAUDE.md.template": [
    "3266e9ac87845042d919de13e44c073d3845ed598badcde86074073311f67fc1",
    "602ce34c60934cbf4e26a976280bceb76fe3bdd55bd7805a6f1ced7d826c4b16",
    "7de6301c41aff4b341902ba2e1a3769201705ec9cd4be4ef1adeb8a79ffa065d"
  ],
  "promptcode-usage.mdc": [
    "cc9ffcd7bbd5920a9f5d79908c40bc13e3946621cbee24623bc0abf3b334d7e1"
  ],
  "promptcode-preset-to-prompt.mdc": [
    "6bafc504afe719f083019025326a95e416d27bf6a32f5edcbc7a5e01e30116e1"
  ],
  "promptcode-preset-list.mdc": [
    "77ed93f774f3d1a47bc5d21342594c68aa7f3fb4733a2e786452b780af65605d"
  ],
  "promptcode-preset-info.mdc": [
    "1fa6ee9037a46bef55039a2f4ec06be5b493833e6efe6de0e2506424170e002d",
    "d9faaeee858e4cdf6c5b6aad2e6f6816eae403db6ea586405a88d4427bab1a39"
  ],
  "promptcode-preset-create.mdc": [
    "65b1edbe2ff662af74feb54acde66965b23c97101b8645194698573f11cc0939",
    "468b8549f45ba8072e15140ff4d1324e11a7c67b7f5a04c74430baa5993ff7ed"
  ],
  "promptcode-ask-expert.mdc": [
    "919bdae89190e2915c7c5a360a4fde480d4f6a8beb5327d66e89294e8bc591d6"
  ]
};

/**
 * Check if a file content matches any known template version
 */
export function isKnownTemplateVersion(fileName: string, checksum: string): boolean {
  const known = TEMPLATE_CHECKSUMS[fileName];
  return known ? known.includes(checksum) : false;
}

/**
 * Get all known checksums for a template file
 */
export function getKnownChecksums(fileName: string): string[] {
  return TEMPLATE_CHECKSUMS[fileName] || [];
}
