/**
 * Auto-generated template checksums
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-checksums.js
 */

export const TEMPLATE_CHECKSUMS: Record<string, string[]> = {
  "promptcode-preset-to-prompt.md": [
    "dc46c41019c808d95fddfa5c6149ce01b117be03ac0b277fc50f61c92c5dedda"
  ],
  "promptcode-preset-list.md": [
    "e1481e4750c5a72d966720803e291b098bb4d41010b814fda034a1406b5b197c"
  ],
  "promptcode-preset-info.md": [
    "da52a33a0efdf19fbad0559babc0844e48d93ed8eef00afb83e8cf7f054a1d7f"
  ],
  "promptcode-preset-create.md": [
    "105cc9379648d75bc3b3fc2cc99088d89e00d8224f7a774857bb6c0c9f821895",
    "5fe5043502b273103d422a945c6181b9136d6ea97e9cfd2282eaa1b96c7c2766"
  ],
  "promptcode-ask-expert.md": [
    "0ee331e5b6fc770965cf7a0576612831c9ae86613058adabc8a6938cf66b6996",
    "11c4de5e1055bd8427d2a4ef48b56177f63b71eecc7057fb4bd51b8246c45991"
  ],
  "CLAUDE.md.template": [
    "3266e9ac87845042d919de13e44c073d3845ed598badcde86074073311f67fc1"
  ],
  "promptcode-usage.mdc": [
    "cc9ffcd7bbd5920a9f5d79908c40bc13e3946621cbee24623bc0abf3b334d7e1",
    "9019a9270e0f4afc993445f7c5fdd26c981cc172d1cd97a8a317f5e60b3e0a66"
  ],
  "promptcode-preset-to-prompt.mdc": [
    "6bafc504afe719f083019025326a95e416d27bf6a32f5edcbc7a5e01e30116e1",
    "3fa2fe13533614b14d869e2397e2982e6412704ca16c241a9b528a4373fd1f62"
  ],
  "promptcode-preset-list.mdc": [
    "77ed93f774f3d1a47bc5d21342594c68aa7f3fb4733a2e786452b780af65605d",
    "97269f790001e7382a80d61a8cfd4177016bb2d4da936bb4eebcec6057caa68a"
  ],
  "promptcode-preset-info.mdc": [
    "d9faaeee858e4cdf6c5b6aad2e6f6816eae403db6ea586405a88d4427bab1a39",
    "5555e6b91c8b80ea7a2033248c108b11b11a7839bf881c12947e38dbbb25d5f0"
  ],
  "promptcode-preset-create.mdc": [
    "468b8549f45ba8072e15140ff4d1324e11a7c67b7f5a04c74430baa5993ff7ed",
    "0e49b39aa98c8ff8128de86d9369224d896a8b30b072e9d43ba984b94a80a6f6"
  ],
  "promptcode-ask-expert.mdc": [
    "919bdae89190e2915c7c5a360a4fde480d4f6a8beb5327d66e89294e8bc591d6",
    "009542c1063fe7bdd0b6d4338ce68d01a7a87ee11310265920c04bc2a0682238"
  ]
};

/**
 * Check if a file content matches any known template version
 */
export function isKnownTemplateVersion(fileName: string, checksum: string): boolean {
  const known = TEMPLATE_CHECKSUMS[fileName];
  return known ? known.includes(checksum) : false;
}

/**
 * Get all known checksums for a template file
 */
export function getKnownChecksums(fileName: string): string[] {
  return TEMPLATE_CHECKSUMS[fileName] || [];
}
