name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allows manual testing from any branch

jobs:
  build-extension:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build VS Code extension
        run: |
          npm run build:core
          npm run vscode:prepublish
          npx @vscode/vsce package --no-dependencies
          
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'

  build-cli:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-x64
            binary-name: promptcode-linux-x64
            bun-target: bun-linux-x64
          - os: macos-latest
            target: darwin-arm64
            binary-name: promptcode-darwin-arm64
            bun-target: bun-darwin-arm64
          - os: macos-latest
            target: darwin-x64
            binary-name: promptcode-darwin-x64
            bun-target: bun-darwin-x64
          - os: windows-latest
            target: win-x64
            binary-name: promptcode-win-x64.exe
            bun-target: bun-windows-x64
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install root dependencies
        run: npm ci
        
      - name: Build core package
        run: npm run build:core
      
      - uses: oven-sh/setup-bun@v2
        
      - name: Install CLI dependencies
        run: |
          cd packages/cli
          bun install
          
      - name: Inject version and build CLI binary
        run: |
          cd packages/cli
          # Update version in package.json to match tag
          VERSION="${{ github.ref_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix if present
          npm version $VERSION --no-git-tag-version --allow-same-version
          # Build with production flag and target architecture
          PROD_BUILD=1 node scripts/inject-version.js
          bun build src/index.ts --compile --target=${{ matrix.bun-target }} --outfile dist/promptcode
          npm run copy-templates
        shell: bash
          
      - name: Rename binary
        run: |
          cd packages/cli/dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv promptcode.exe ../${{ matrix.binary-name }}
          else
            mv promptcode ../${{ matrix.binary-name }}
          fi
        shell: bash
        
      - name: Generate checksum
        run: |
          cd packages/cli
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            # certutil outputs multiple lines, we need just the hash
            certutil -hashfile ${{ matrix.binary-name }} SHA256 | head -2 | tail -1 | tr -d ' ' | tr '[:upper:]' '[:lower:]' > temp_hash
            echo "$(cat temp_hash)  ${{ matrix.binary-name }}" > ${{ matrix.binary-name }}.sha256
            rm temp_hash
          else
            shasum -a 256 ${{ matrix.binary-name }} > ${{ matrix.binary-name }}.sha256
          fi
        shell: bash
        
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.target }}
          path: |
            packages/cli/${{ matrix.binary-name }}
            packages/cli/${{ matrix.binary-name }}.sha256

  create-release:
    needs: [build-extension, build-cli]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vsix/*.vsix
            cli-*/*
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## Installation

            ### VS Code Extension
            1. Download `promptcode-${{ github.ref_name }}.vsix`
            2. Install via Command Palette: `Extensions: Install from VSIX...`
            3. Or via CLI: `code --install-extension promptcode-${{ github.ref_name }}.vsix`

            ### CLI Tool

            #### Quick Install (Recommended)
            **macOS/Linux:**
            ```bash
            curl -fsSL https://raw.githubusercontent.com/cogflows/promptcode-vscode/main/packages/cli/scripts/install.sh | bash
            ```

            **Windows (PowerShell):**
            ```powershell
            irm https://raw.githubusercontent.com/cogflows/promptcode-vscode/main/packages/cli/scripts/install.ps1 | iex
            ```

            #### Manual Installation
            1. Download the appropriate binary for your platform from the assets below
            2. Make it executable: `chmod +x promptcode-*` (Mac/Linux)
            3. Move to PATH: `sudo mv promptcode-* /usr/local/bin/promptcode`
            4. Run: `promptcode --help`

            ### Features
            - ✨ **Self-updating**: Run `promptcode self-update` to get the latest version
            - 🤖 **Claude Code Integration**: Auto-detects and configures for Claude projects
            - 🗑️ **Clean uninstall**: Run `promptcode uninstall` to remove completely

            See [README](https://github.com/cogflows/promptcode-vscode) for detailed documentation.